
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipqpcofvpnlwueinoidv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwcXBjb2Z2cG5sd3VlaW5vaWR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODAyNjksImV4cCI6MjA2MTY1NjI2OX0.xf3SVAQptJjL6igPkrq_aJuZXI4QhrbfB3SN1IPFRss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  }
});
